# Generated by Django 2.2 on 2019-04-09 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Markup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('memo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('operation_name', models.CharField(max_length=200)),
                ('operation_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('online', models.BooleanField()),
                ('group_id', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('operation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Operation')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.User')),
            ],
        ),
    ]
