# Generated by Django 2.2 on 2019-04-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color', models.CharField(max_length=6)),
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
